#! /usr/bin/env ruby
# Blobec: Git with GPG on FTP
#--
# Copyright (C) 2010 Martin Vidner
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of version 2 of the GNU General Public License
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#++

require "pp"
#require "uri"
require "rubygems"
require "rake"
require "fileutils"

require 'optparse'

$remote = "origin"
$verbose = false

opts = OptionParser.new "Usage: blobec [options] command [file ...]"
opts.on("-r", "--remote NAME", String) {|n| $remote = n }
opts.on("-v", "--verbose", "Run verbosely") {|v| $verbose = v }
opts.on_tail("-h", "--help", "Show this message") do
  puts opts
  exit
end

command, filename = opts.parse(*ARGV)
if command
  filename ||= "MYFILE"         # FIXME
else
  puts opts
  exit
end

def url_for(filename)
  begin
    f = File.new(filename + ".blburl." + $remote)
    f.readline.chomp
  rescue Errno::ENOENT
    `git config --get blobec.#{$remote}.url`.chomp
  end
end

def local_url(filename)
  "file://" + File.expand_path(filename)
end

def sys(array)
  sh *array
end

def echo_system(*args)
  puts args.join " "
  system *args
end

module Blobec
  module Transport
    module Ftp
      extend self

      # url -> filename
      def get(url, filename)
        curl %w{--remote-time --output} + [filename, url.to_s]
      end

      # filename -> url
      def put(filename, url)
        curl ["--upload-file", filename, url.to_s]
      end

      COUNT = 3
      SLEEP = 5
      def lock(*args)
        COUNT.times do |i|
          result = lock_once(*args)
          return result unless result.nil?
          if i == COUNT-1
            puts "Lock failed"
            return nil
          end
          puts "Will retry #{COUNT-1 - i} times after #{SLEEP} seconds"
          sleep SLEEP
        end
        # not reached
        nil
      end

      def lock_once(url)
        locked_url = url + ".locked"
        dir, slash, base = url.rpartition "/"
        mv(dir + "/", base, base + ".locked") && locked_url || nil
      end

      def unlock(url)
        dir, slash, base = url.rpartition "/"
        mv(dir + "/", base + ".locked", base)
      end

      private

#      CURL_FLAGS = %w{--verbose --netrc-optional --ftp-ssl --insecure}
      CURL_FLAGS = %w{--netrc-optional --ftp-ssl --insecure}

      def curl(array)
        # insecure sucks. should --cacert help?
        sys %w{curl} + CURL_FLAGS + array
      end

      def mv(path, from, to)
        args = ["curl", CURL_FLAGS, "-f", "-Q", "+RNFR #{from}", "-Q", "+RNTO #{to}", "--range", "0-0", "-o", "/dev/null", path + to].flatten
        echo_system(*args)
        $?.success?
      end

      # these are obsolete?
      def upload_ts(url, filename)
        upload url, filename
        tfn = filename + ".timestamp"
        timestamp(url, tfn)
        theirs_ts = mtime(tfn)
        File.utime(0, theirs_ts, filename)
        rm tfn
      end

      def timestamp(url, filename)
        curl %w{--remote-time --range 0-0 --output} + [filename, url.to_s]
      end

      def mtime(filename)
        File.new(filename).mtime
      end
    end # module Ftp

    module File
      extend self

      # url -> filename
      def get(url, filename)
        FileUtils.cp remote_filename(url), filename
      end

      # filename -> url
      def put(filename, url)
        p self
        FileUtils.cp filename, remote_filename(url)
      end

      # TODO ensure that create will not kill an existing blob
      def create
        FileUtils.touch remote_filename
      end

      private

      def remote_filename(url)
        url.sub %r{^file://}, ""
      end
    end # module File
  end # module Transport

  module Wrap
    extend self

    def wrap(git_dir, pack_filename)
      local = local_url(git_dir)
      git = git_dir
      mktemp(git_dir + ".tar.XXXXXX") do |tar|
        verbose = $verbose? "v": ""  
        sys %W{tar c#{verbose}f} + [tar, "-C", git, "."]
        sys %w{gpg --encrypt --yes --default-recipient-self --output} + [pack_filename, tar]
      end
    end  

    # empty git_dir needs to exist already
    def unwrap(pack_filename, git_dir)
      git = nil
      mktemp(pack_filename + ".tar.XXXXXX") do |tar|
        # interactive (yes=overwrite existing file)
        sys %w{gpg --decrypt --yes --output} + [tar, pack_filename]
        verbose = $verbose? "v": ""  
        sys %w{tar -f} + [tar, "-C", git_dir, "-x#{verbose}"]
      end
      git
    end
  end

  module Vcs
    module Git
      extend self

      # compare two blobs
      # newer, equal, DIVERGED=nil
      def compare(a, b)
        atob = dry_push a, b
        btoa = dry_push b, a
        both = atob + btoa
        if both < -1 or both > 1
          nil
        else
          both
        end
      end

      def dry_push(dir_a, dir_b)
        out = `cd #{dir_a}; git push --dry-run --verbose --porcelain #{dir_b}`
        if $?.success # a >= b
          results = out.grep /^[ =!]/ # space:success, =:unchanged, !:failed
          if results.all? {|r| r =~ /^=/ }
            0                   # equal
          else
            1                   # at least 1 fast forward: a > b
          end
        else
          -1                    # push failed: a < b or something else
        end
      end
    end
  end
end

require "fileutils"
include FileUtils

def merge(theirs, mine, result)
  puts "MERGE", theirs, mine, result
  if identical? theirs, mine
    mv theirs, result
    rm mine
    puts "SAME CONTENT"
  end
end

def update(filename)
  url = url_for(filename)
  tfn = filename + ".timestamp"
  timestamp(url, tfn)
  mine_ts = mtime(filename)
  theirs_ts = mtime(tfn)
  if theirs_ts == mine_ts
    puts "SAME TIMESTAMP"
    return
  end
  theirs_fn = filename + ".theirs"
  download(url, theirs_fn)
  mine_fn = filename + ".mine"
  mv filename, mine_fn
  merge theirs_fn, mine_fn, filename
end

def mktemp(template)
  t = `mktemp #{template}`.chomp
  fail unless $?.success?
  if block_given?
    begin
      yield t
    ensure
      rm_r t
    end
  else
    t
  end
end

def git_push(source_git, target_git)
  push = "git push --verbose --porcelain"
  echo_system "cd #{source_git}; #{push} #{local_url(target_git)}"
  $?.success?
end

def wrapped_git_push(git_local, gtg_target)
  status = nil
  mktemp("-d #{gtg_target}.bare.git.XXXXXX") do |git_target|
    Blobec::Wrap.unwrap(gtg_target, git_target)
    status = git_push(git_local, git_target)
    if status
      Blobec::Wrap.wrap(git_target, gtg_target)
    end
  end
  status
end

def push(git_dir, url, transport)
  locked_url = transport.lock(url)
  unless locked_url.nil?
    begin
      mktemp locked_url[%r{.*/(.*)},1] + ".proxy.XXXXXX" do |proxy|
        transport.get(locked_url, proxy)
        if wrapped_git_push(git_dir, proxy)
          transport.put(proxy, locked_url)
        end
      end
    ensure
      transport.unlock(url)
    end
  end
end

def fetch(url, filename, transport)
  mktemp url[%r{.*/(.*)},1] + ".proxy.XXXXXX" do |proxy|
    transport.get(url, proxy)
    mktemp("-d #{proxy}.bare.git.XXXXXX") do |proxy_git|
      Blobec::Wrap.unwrap(proxy, proxy_git)
      sh "cd #{filename} && " +
        "git remote rm #{$remote} && " +
        "git remote add #{$remote} #{local_url(proxy_git)} && " +
        "git fetch #{$remote}"
    end
  end
end

url = url_for filename
# -> factory method in Blobec
transport = Blobec::Transport.const_get(url.sub(/:.*/, "").capitalize)

case command
# low level transport commands
when "get"
  transport.get(url, filename)
when "put"
  transport.put(filename, url)
when "lock"
  locked_url = transport.lock(url)
  puts locked_url || "FAILED"
when "unlock"
  transport.unlock(url)

when "up", "update":
    update(filename)
when "ci", "checkin":
when "st", "status":
    system "ls -l #{filename}*"
when "upload":
    upload(url, filename)
when "push":
    push(filename, url, transport)
when "fetch":
    fetch url, filename, transport
when "create":
    transport.create
else
    $stderr.puts "Unknown command '#{command}'"
end
